# Generated by Django 4.2.23 on 2025-08-13 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typeRecette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOrdre', models.IntegerField()),
                ('isSection', models.BooleanField(default=False)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('nom', models.TextField()),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOrdre', models.IntegerField()),
                ('description', models.TextField()),
                ('isSection', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'preparation',
                'verbose_name_plural': 'preparations',
                'db_table': 'preparation',
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('portion', models.IntegerField()),
                ('image', models.BinaryField(blank=True, null=True)),
                ('conseil', models.TextField(blank=True, null=True)),
                ('typeRecette', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='typeRecette.typerecette')),
            ],
            options={
                'verbose_name': 'recette',
                'verbose_name_plural': 'recettes',
                'db_table': 'recette',
            },
        ),
    ]
