# Generated by Django 4.2.23 on 2025-08-13 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recette.recette', verbose_name='Recette'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recette.recette', verbose_name='Recette'),
        ),
        migrations.AlterUniqueTogether(
            name='recette',
            unique_together={('titre', 'typeRecette')},
        ),
    ]
