# Generated by Django 4.2.23 on 2025-08-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_recettes'),
        ('recette', '0003_alter_ingredient_recette_alter_preparation_recette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='tags',
            field=models.ManyToManyField(to='tag.tag'),
        ),
    ]
