# Generated by Django 4.2.23 on 2025-08-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0004_recette_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='tags',
        ),
    ]
