# Generated by Django 4.2.23 on 2025-09-21 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0006_alter_recette_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('nomPluriel', models.TextField()),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'db_table': 'produit',
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOrdre', models.IntegerField()),
                ('code', models.TextField(max_length=5)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'unité',
                'verbose_name_plural': 'unités',
                'db_table': 'unite',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recette.unite'),
        ),
    ]
