# Generated by Django 4.2.23 on 2025-09-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0007_produit_unite_ingredient_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unite',
            name='noOrdre',
        ),
    ]
