# Generated by Django 4.2.23 on 2025-09-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0008_remove_unite_noordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='borneSuperieur',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='uniteSuperieur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recette.unite', verbose_name='Unité superieur'),
        ),
    ]
