# Generated by Django 4.2.23 on 2025-09-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0009_unite_bornesuperieur_unite_unitesuperieur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='borneSuperieur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unite',
            name='uniteSuperieur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recette.unite', verbose_name='Unité superieur'),
        ),
    ]
