# Generated by Django 4.2.23 on 2025-09-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0010_alter_unite_bornesuperieur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recette.produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='determinant',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
