# Generated by Django 4.2.23 on 2025-10-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0011_ingredient_produit_produit_determinant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='nom',
            field=models.TextField(null=True),
        ),
    ]
