# Generated by Django 4.2.23 on 2025-10-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0012_alter_ingredient_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='determinant',
        ),
    ]
