# Generated by Django 4.2.23 on 2025-10-18 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0013_remove_produit_determinant'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='produitDeBase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recette.produit', verbose_name='Produit de base'),
        ),
    ]
