# Generated by Django 4.2.23 on 2025-10-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0014_produit_produitdebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='nom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
