# Generated by Django 4.2.23 on 2025-10-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0015_alter_ingredient_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recette.produit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recette.unite'),
        ),
    ]
