# Generated by Django 4.2.23 on 2025-10-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0016_alter_ingredient_produit_alter_ingredient_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='determinant',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
