# Generated by Django 4.2.23 on 2025-11-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0017_produit_determinant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.TextField(unique=True),
        ),
    ]
