# Generated by Django 4.2.23 on 2025-11-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typeRecette', '0003_alter_typerecette_user'),
        ('recette', '0018_alter_produit_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='typeRecette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='typeRecette.typerecette', verbose_name='Type de recette'),
        ),
    ]
