# Generated by Django 4.2.23 on 2026-01-10 07:14

from django.db import migrations, models
import recette.models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0021_alter_recette_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='imagefield',
            field=models.ImageField(blank=True, null=True, upload_to=recette.models.path_and_rename),
        ),
    ]
