# Generated by Django 4.2.23 on 2026-01-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0022_alter_recette_imagefield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='imagefield',
            new_name='imageNew',
        ),
        migrations.RenameField(
            model_name='recette',
            old_name='image',
            new_name='imageOld',
        ),
    ]
