# Generated by Django 4.2.23 on 2026-01-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0023_rename_imagefield_recette_imagenew_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='imageNew',
            new_name='image',
        ),
    ]
