# Generated by Django 4.2.23 on 2026-01-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typeRecette', '0003_alter_typerecette_user'),
        ('recette', '0024_rename_imagenew_recette_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recette.produit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recette.unite'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='produitDeBase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recette.produit', verbose_name='Produit de base'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='typeRecette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='typeRecette.typerecette', verbose_name='Type de recette'),
        ),
        migrations.AlterField(
            model_name='unite',
            name='uniteSuperieur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recette.unite', verbose_name='Unité superieur'),
        ),
    ]
