# Generated by Django 6.0.2 on 2026-09-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0025_alter_ingredient_produit_alter_ingredient_unite_and_more'),
        ('typeRecette', '0004_typerecette_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='typeRecette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typeRecette.typerecette', verbose_name='Type de recette'),
        ),
    ]
