# Generated by Django 4.2.23 on 2025-08-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='recettes',
        ),
    ]
