# Generated by Django 4.2.23 on 2025-08-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0005_remove_recette_tags'),
        ('tag', '0002_remove_tag_recettes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='recettes',
            field=models.ManyToManyField(to='recette.recette'),
        ),
    ]
