# Generated by Django 4.2.23 on 2025-12-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('support', models.CharField(choices=[('apk', 'Android'), ('exe', 'Windows'), ('app', 'Mac'), ('ipa', 'ios')], default='fr', max_length=8)),
            ],
        ),
    ]
