# Generated by Django 4.2.23 on 2025-12-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVersion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='support',
            field=models.CharField(choices=[('app', 'Mac'), ('apk', 'Android'), ('exe', 'Windows'), ('ipa', 'ios')], default='fr', max_length=8),
        ),
    ]
