# Generated by Django 4.2.23 on 2025-12-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVersion', '0002_alter_appversion_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appversion',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='appversion',
            name='support',
            field=models.CharField(choices=[('app', 'Mac'), ('exe', 'Windows'), ('apk', 'Android'), ('ipa', 'ios')], default='fr', max_length=8),
        ),
    ]
