# Generated by Django 4.2.23 on 2025-12-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVersion', '0003_remove_appversion_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='support',
            field=models.CharField(choices=[('exe', 'Windows'), ('ipa', 'ios'), ('app', 'Mac'), ('apk', 'Android')], max_length=8),
        ),
    ]
