# Generated by Django 4.2.23 on 2025-12-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVersion', '0004_alter_appversion_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='support',
            field=models.CharField(choices=[('apk', 'Android'), ('exe', 'Windows'), ('app', 'Mac'), ('ipa', 'ios')], max_length=8),
        ),
    ]
