# Generated by Django 4.2.23 on 2025-12-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVersion', '0005_alter_appversion_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='support',
            field=models.CharField(choices=[('ipa', 'ios'), ('apk', 'Android'), ('app', 'Mac'), ('exe', 'Windows')], max_length=8),
        ),
    ]
