# Generated by Django 4.2.23 on 2025-08-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOrdre', models.IntegerField(blank=True, db_column='noOrdre', null=True)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'type de recette',
                'verbose_name_plural': 'types de recette',
                'db_table': 'type_recette',
            },
        ),
    ]
