# Generated by Django 6.0.2 on 2026-09-23 11:41

import typeRecette.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeRecette', '0003_alter_typerecette_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='typerecette',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=typeRecette.models.path_and_rename),
        ),
    ]
