# Generated by Django 4.2.23 on 2025-09-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'Anglais'), ('fr', 'Francais')], default='fr', max_length=8),
        ),
    ]
