# Generated by Django 4.2.23 on 2025-12-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('fr', 'Francais'), ('en', 'Anglais')], default='fr', max_length=8),
        ),
    ]
